apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budget-app-web
  template:
    metadata:
      labels:
        app: budget-app-web
    spec:
      containers:
        - name: budget-app
          image: bhargavibairagoni/budget-app-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: budget-app-db
            - name: DATABASE_NAME
              value: budgetdb
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: password
