apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: budget-app-db
spec:
  selector:
    matchLabels:
      app: budget-app-db
  serviceName: "budget-app-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: budget-app-db
    spec:
      containers:
        - name: postgres
          image: bhargavibairagoni/postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: budgetdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
