version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Budgy_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/Budgy_development
      # Optional: RAILS_MAX_THREADS, etc
    depends_on:
      - db

volumes:
  pgdata:

